### ISSUE TITLE
Unable to resolve dependencies

### ISSUE THREAD

**Issue by dspescha-eth** [spark-notebook/spark-notebook#733]
We are upgrading from Spark Notebook 0.63 with Spark 1.6.1 and Scala 2.10 to the current master of the Notebook, Spark 2.0.1 and Scala 2.11.

Now we are encountering problems when resolving maven-dependencies. We use the same configuration as in the old setup (i.e. configuring a http proxy to reach the remote maven central etc).

when I type

`:dp org.apache.commons % commons-math3 % 3.6.1`

in the notebook (or add this entry as customDeps in the notebook metadata -> same result), i get the following exception:

```
2016-10-27 10:12:07,847  WARN [Remote-akka.actor.default-dispatcher-15] (com.jcabi.aether.Aether) - mirrors: []
2016-10-27 10:12:07,859  WARN [FileRepositoryConnector-1] (com.jcabi.aether.LogTransferListener) - #transferFailed('GET FAILED file:/home/ORG/myuser/.m2/repository/..143..ommons-math3/3.6.1/commons-math3-3.6.1.pom'): in 23.18µs
2016-10-27 10:12:07,859  INFO [Remote-akka.actor.default-dispatcher-15] (com.ning.http.client.providers.netty.NettyAsyncHttpProvider) - Number of application's worked threads is 48
2016-10-27 10:12:07,869  WARN [Remote-akka.actor.default-dispatcher-15] (com.jcabi.aether.LogTransferListener) - #transferFailed('GET FAILED http://repo1.maven.org/maven2/org/apac..135..ommons-math3/3.6.1/commons-math3-3.6.1.pom'): in 21.19µs
2016-10-27 10:12:07,872  INFO [Remote-akka.actor.default-dispatcher-15] (com.ning.http.client.providers.netty.NettyAsyncHttpProvider) - Number of application's worked threads is 48
2016-10-27 10:12:07,880  WARN [Remote-akka.actor.default-dispatcher-15] (com.jcabi.aether.LogTransferListener) - #transferFailed('GET FAILED http://dl.bintray.com/spark-packages/m..148..ommons-math3/3.6.1/commons-math3-3.6.1.pom'): in 13.99µs
2016-10-27 10:12:07,882  INFO [Remote-akka.actor.default-dispatcher-15] (com.ning.http.client.providers.netty.NettyAsyncHttpProvider) - Number of application's worked threads is 48
2016-10-27 10:12:07,888  WARN [Remote-akka.actor.default-dispatcher-15] (com.jcabi.aether.LogTransferListener) - #transferFailed('GET FAILED https://oss.sonatype.org/content/repos..160..ommons-math3/3.6.1/commons-math3-3.6.1.pom'): in 24.10µs
2016-10-27 10:12:07,893 ERROR [Remote-akka.actor.default-dispatcher-15] (com.jcabi.aether.Aether) - #resolve(org.apache.commons:commons-math3:jar:3.6.1, 'runtime', notebook.util.Deps$$anon$1@7603eab7): thrown org.sonatype.aether.resolution.DependencyResolutionException(failed to load 'org.apache.commons:commons-math3:jar:3.6.1 (runtime)' from ["Maven2 local (file:/home/ORG/myuser/.m2/repository/, releases+snapshots) without authentication", "maven-central (http://repo1.maven.org/maven2/, releases+snapshots) without authentication", "spark-packages (http://dl.bintray.com/spark-packages/maven/, releases+snapshots) without authentication", "oss-sonatype (https://oss.sonatype.org/content/repositories/releases/, releases+snapshots) without authentication"] into /tmp/spark-notebook/aether/4001a417-8c81-4efc-96b0-a003949b201a) out of com.jcabi.aether.Aether#fetch[237] in 45ms
2016-10-27 10:12:07,893 ERROR [Remote-akka.actor.default-dispatcher-15] (Aether downloads) - Failed to resolve dependencies: 
org.apache.commons % commons-math3 % 3.6.1
org.sonatype.aether.resolution.DependencyResolutionException: failed to load 'org.apache.commons:commons-math3:jar:3.6.1 (runtime)' from ["Maven2 local (file:/home/ORG/myuser/.m2/repository/, releases+snapshots) without authentication", "maven-central (http://repo1.maven.org/maven2/, releases+snapshots) without authentication", "spark-packages (http://dl.bintray.com/spark-packages/maven/, releases+snapshots) without authentication", "oss-sonatype (https://oss.sonatype.org/content/repositories/releases/, releases+snapshots) without authentication"] into /tmp/spark-notebook/aether/4001a417-8c81-4efc-96b0-a003949b201a
    at com.jcabi.aether.Aether.fetch(Aether.java:237)
    at com.jcabi.aether.Aether.resolve_aroundBody2(Aether.java:180)
    at com.jcabi.aether.Aether$AjcClosure3.run(Aether.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
    at com.jcabi.aether.Aether.resolve(Aether.java:177)
    at notebook.util.Deps$.resolve(Deps.scala:198)
    at notebook.util.Deps$$anonfun$19$$anonfun$apply$15$$anonfun$apply$16.apply(Deps.scala:223)
    at notebook.util.Deps$$anonfun$19$$anonfun$apply$15$$anonfun$apply$16.apply(Deps.scala:223)
    at scala.util.Try$.apply(Try.scala:192)
    at notebook.util.Deps$$anonfun$19$$anonfun$apply$15.apply(Deps.scala:223)
    at notebook.util.Deps$$anonfun$19$$anonfun$apply$15.apply(Deps.scala:223)
    at scala.util.Success.flatMap(Try.scala:231)
    at notebook.util.Deps$$anonfun$19.apply(Deps.scala:223)
    at notebook.util.Deps$$anonfun$19.apply(Deps.scala:222)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
    at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
    at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
    at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
    at notebook.util.Deps$.script(Deps.scala:222)
    at notebook.client.ReplCalculator$$anonfun$13$$anon$1.execute(ReplCalculator.scala:269)
    at notebook.client.ReplCalculator$$anonfun$13$$anon$1$$anonfun$receive$1.applyOrElse(ReplCalculator.scala:201)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
    at notebook.client.ReplCalculator$$anonfun$13$$anon$1.aroundReceive(ReplCalculator.scala:167)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: failed to load 'org.apache.commons:commons-math3:jar:3.6.1 (runtime)' from ["Maven2 local (file:/home/ORG/myuser/.m2/repository/, releases+snapshots) without authentication", "maven-central (http://repo1.maven.org/maven2/, releases+snapshots) without authentication", "spark-packages (http://dl.bintray.com/spark-packages/maven/, releases+snapshots) without authentication", "oss-sonatype (https://oss.sonatype.org/content/repositories/releases/, releases+snapshots) without authentication"] into /tmp/spark-notebook/aether/4001a417-8c81-4efc-96b0-a003949b201a
    ... 36 more
Caused by: java.lang.NullPointerException
    at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:352)
    at com.jcabi.aether.Aether.fetch(Aether.java:228)
    ... 35 more
2016-10-27 10:12:07,894 ERROR [Remote-akka.actor.default-dispatcher-4] (notebook.client.ReplCalculator) - Cannot add dependencies
org.sonatype.aether.resolution.DependencyResolutionException: failed to load 'org.apache.commons:commons-math3:jar:3.6.1 (runtime)' from ["Maven2 local (file:/home/ORG/myuser/.m2/repository/, releases+snapshots) without authentication", "maven-central (http://repo1.maven.org/maven2/, releases+snapshots) without authentication", "spark-packages (http://dl.bintray.com/spark-packages/maven/, releases+snapshots) without authentication", "oss-sonatype (https://oss.sonatype.org/content/repositories/releases/, releases+snapshots) without authentication"] into /tmp/spark-notebook/aether/4001a417-8c81-4efc-96b0-a003949b201a
    at com.jcabi.aether.Aether.fetch(Aether.java:237)
    at com.jcabi.aether.Aether.resolve_aroundBody2(Aether.java:180)
    at com.jcabi.aether.Aether$AjcClosure3.run(Aether.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:208)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
    at com.jcabi.aether.Aether.resolve(Aether.java:177)
    at notebook.util.Deps$.resolve(Deps.scala:198)
    at notebook.util.Deps$$anonfun$19$$anonfun$apply$15$$anonfun$apply$16.apply(Deps.scala:223)
    at notebook.util.Deps$$anonfun$19$$anonfun$apply$15$$anonfun$apply$16.apply(Deps.scala:223)
    at scala.util.Try$.apply(Try.scala:192)
    at notebook.util.Deps$$anonfun$19$$anonfun$apply$15.apply(Deps.scala:223)
    at notebook.util.Deps$$anonfun$19$$anonfun$apply$15.apply(Deps.scala:223)
    at scala.util.Success.flatMap(Try.scala:231)
    at notebook.util.Deps$$anonfun$19.apply(Deps.scala:223)
    at notebook.util.Deps$$anonfun$19.apply(Deps.scala:222)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
    at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
    at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
    at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
    at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
    at notebook.util.Deps$.script(Deps.scala:222)
    at notebook.client.ReplCalculator$$anonfun$13$$anon$1.execute(ReplCalculator.scala:269)
    at notebook.client.ReplCalculator$$anonfun$13$$anon$1$$anonfun$receive$1.applyOrElse(ReplCalculator.scala:201)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
    at notebook.client.ReplCalculator$$anonfun$13$$anon$1.aroundReceive(ReplCalculator.scala:167)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: failed to load 'org.apache.commons:commons-math3:jar:3.6.1 (runtime)' from ["Maven2 local (file:/home/ORG/myuser/.m2/repository/, releases+snapshots) without authentication", "maven-central (http://repo1.maven.org/maven2/, releases+snapshots) without authentication", "spark-packages (http://dl.bintray.com/spark-packages/maven/, releases+snapshots) without authentication", "oss-sonatype (https://oss.sonatype.org/content/repositories/releases/, releases+snapshots) without authentication"] into /tmp/spark-notebook/aether/4001a417-8c81-4efc-96b0-a003949b201a
    ... 36 more
Caused by: java.lang.NullPointerException
    at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:352)
    at com.jcabi.aether.Aether.fetch(Aether.java:228)
    ... 35 more

```

I also tried to configure our company nexus repository as a mirror for the maven central, still the same exception... so I guess it has nothing to do with wrong proxy settings.

Can you give us any hints on what to try out next?

**Comment by andypetrella** [comment]
Thanks for the detailed info!
Can you tell me more about the proxy settings, how you configured it?
All in all it's easy to check if it is the problem, if it fails the same way for other deps, then it's probably the culprit.

Maybe that would be different between the 2.10 and 2.11, that's something worth checking, probably on our side though :-)

**Comment by raproth** [comment]
I tried to configure the proxy in several ways:

in conf/application.conf:


```
http {
  proxyHost = localhost
  proxyPort = 3128
#   proxyUser = ...
#   proxyPassword = ...
#   nonProxyHosts = ...
}
```

And in the notebook-metadata:

`"spark.driver.extraJavaOption": "-Dhttp.proxyHost=localhost -Dhttp.proxyPort=3128 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=3128"`

And I also have it configured in in $MAVEN_HOME/conf/settings.xml, although I'm not sure this has any influence.

(sorry, I was logged in with a wrong user when I posted the question)

**Comment by andypetrella** [comment]
maybe using: https://github.com/andypetrella/spark-notebook/blob/master/conf/application.conf#L229 would help.
Also, if you want to add options to the driver/spawned process/notebook you can simply use `customArgs` in the metadata.

lmk

**Comment by raproth** [comment]
This didn't help

```
remote-repos {
  proxy {
     protocol = http
     host     = localhost
     port     = 3128
    # "username" = ...,
    # "password" = ...,
    # "nonProxyHosts" = ...
  }
}

```

**Comment by andypetrella** [comment]
damn, would you have the same crap even with another deps? if you replace this one with another?

Would be worth to remove all deps also and check what is finally in the notebook's java props, sys env and such. Just to see if everything is available in the process

**Comment by raproth** [comment]
yes I have the problems also with other dependencies.

But now I've installed the same Spark-Notebook in my personal Ubuntu VM where I have free access the the internet, and there I don't encounter the described problems. So there must be something wrong with configuration on our (company) server

**Comment by andypetrella** [comment]
God damn it, using the same configuration ?
It's either in the configuration, or the way proxy is used in the spark notebook :-S

**Comment by raproth** [comment]
The VM is not the same OS (Ubuntu) than our production server (Red Hat), but both with the same code of the spark notebook and same configuration (except proxy settings).

I will inform you if I can make it work

**Comment by andypetrella** [comment]
mmmh okay, let me know if I can help.
you can also discuss that on the gitter channel

**Comment by raproth** [comment]
I found something which me cause the problem:

in modules/common/src/main/scala-2.11/notebook/util/Deps.scala:49

`val config = ConfigFactory.load().getConfig("remote-repos")`

Aren't we supposed to pass in the location of the config-file, as e.g. done in modules/subprocess/src/main/scala/notebook/kernel/remote/RemoteActorSystem.scala:24

`val cfg = ConfigFactory.load(configFile)`

I seems to me that the actual `application.conf `is not picked up in Deps.scala

**Comment by andypetrella** [comment]
mmmh indeed, however, it should take the `application.conf` file by default on the root of the classpath, do you have your own configuration file? Anyway, you're probably right :-)

Also, this is only used for the `s3` a few lines below (which would mean that `s3` repos won't work I guess), are you using such repos?

**Comment by hblt-j** [comment]
I downloaded the docker version of the trial, increase the dependence on the emergence of suspended animation, what advice?

**Comment by raproth** [comment]
I think this can be closed, it works in the current version (as long as I specify customLocalRepo in the notebook-metadata), see also https://github.com/spark-notebook/spark-notebook/issues/858
