### ISSUE TITLE
Markdown export fails

### ISSUE THREAD

**Issue by maasg** [spark-notebook/spark-notebook#736]
With a fresh download of 0.7.0, `markdown` export fails with:

```
[error] application - Error accessing notebook [core/Simple Spark]
java.io.IOException: No such file or directory
    at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[na:1.8.0_101]
    at java.io.File.createNewFile(File.java:1012) ~[na:1.8.0_101]
    at notebook.export.Markdown$$anonfun$generate$1.apply(Markdown.scala:110) ~[nooostab.spark-notebook-0.7.0-scala-2.10.6-spark-2.0.2-hadoop-2.7.2-with-hive.jar:0.7.0-scala-2.10.6-spark-2.0.2-hadoop-2.7.2-with-hive]
    at notebook.export.Markdown$$anonfun$generate$1.apply(Markdown.scala:74) ~[nooostab.spark-notebook-0.7.0-scala-2.10.6-spark-2.0.2-hadoop-2.7.2-with-hive.jar:0.7.0-scala-2.10.6-spark-2.0.2-hadoop-2.7.2-with-hive]
    at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.6.jar:na]
```

**Comment by vidma** [comment]
old, I guess.

**Comment by scarabsoft** [comment]
Hello out there, 
this error still exists on my machine. I use the latest source of spark.
It has something to do with URL encoding and nested files.

So lets say I have a folder named folder which contains of  an spark notebook Test 1 2 3 4. If I try to export this notebook I get this exception:

`spark-notebook_1  | [info] application - getNotebook at path folder//Test 1 2 3 4 .snb
spark-notebook_1  | [info] application - Loading notebook at path folder//Test 1 2 3 4 .snb
spark-notebook_1  | [error] application - Error accessing notebook [folder//Test 1 2 3 4 ]
spark-notebook_1  | java.io.IOException: No such file or directory
spark-notebook_1  | 	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[na:1.8.0_131]
spark-notebook_1  | 	at java.io.File.createNewFile(File.java:1012) ~[na:1.8.0_131]
spark-notebook_1  | 	at notebook.export.Markdown$$anonfun$generate$1.apply(Markdown.scala:110) ~[nooostab.spark-notebook-0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.8.0.jar:0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.8.0]
spark-notebook_1  | 	at notebook.export.Markdown$$anonfun$generate$1.apply(Markdown.scala:74) ~[nooostab.spark-notebook-0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.8.0.jar:0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.8.0]
`
The URL looks like: http://localhost:9001/nbconvert/markdown/folder/Test%201%202%203%204%20.snb?download=true

/folder **/** Test%201% (whitespace insertion only for bold)

If I encode the slash beteween folder and the notebook name with %2F it will work

http://localhost:9001/notebooks/folder%2FTest%201%202%203%204%20.snb?kernel_name=spark#

/folder **%2F** Test (whitespace insertion only for bold)
