### ISSUE TITLE
Notebook not able to start

### ISSUE THREAD

**Issue by james64** [spark-notebook/spark-notebook#839]
Hey,

I have downloaded new version of SN to stay up-to-date. Now I cannot run any notebook (old or new). This is what I see in a log of nb:

```
2017-04-12 12:49:00,930  INFO [main] (notebook.kernel.pfork.BetterFork$) - Remote process starting
2017-04-12 12:49:01,791  INFO [Remote-akka.actor.default-dispatcher-2] (akka.event.slf4j.Slf4jLogger) - Slf4jLogger started
2017-04-12 12:49:01,848  INFO [Remote-akka.actor.default-dispatcher-2] (Remoting) - Starting remoting
2017-04-12 12:49:02,060  INFO [Remote-akka.actor.default-dispatcher-3] (Remoting) - Remoting started; listening on addresses :[akka.tcp://Remote@127.0.0.1:39001]
2017-04-12 12:49:02,062  INFO [Remote-akka.actor.default-dispatcher-3] (Remoting) - Remoting now listens on addresses: [akka.tcp://Remote@127.0.0.1:39001]
```
This hangs for a while with nb saying "Kernel starting, please wait...". Then nb announces that "Connection failed...". Log of SN server contains only this line:

`INFO application: View notebook 'visnovy-jogurt.snb', presentation: 'None'`

Everything works fine with older version I use (see below).

This might be either a bug or a result of a change in our cluster conf/environment. If you can help me to dig deeper that would be great.

New version where issue happens:
`Build: |
buildTime-Tue Apr 11 11:58:48 UTC 2017 |
formattedShaVersion-0.8.0-SNAPSHOT-fbb8cb7cda2af81473348845c44aa4e14ee9068f |
sbtVersion-0.13.8 | scalaVersion-2.11.8 | sparkNotebookVersion-0.8.0-SNAPSHOT | viewer-false |
hadoopVersion-2.6.0-cdh5.10.1 | jets3tVersion-0.7.1 | jlineDef-(jline,2.12) | sparkVersion-2.1.0
| withHive-false |.`

My current version which works:
`Build: |  buildTime-Mon Jan 30 14:50:08 UTC 2017 | formattedShaVersion-0.8.0-SNAPSHOT-7a4922a46ca9d8d7e85a11fe0bc62db9f115012e | sbtVersion-0.13.8 | scalaVersion-2.11.8 | sparkNotebookVersion-0.8.0-SNAPSHOT | hadoopVersion-2.6.0-cdh5.7.1 | jets3tVersion-0.7.1 | jlineDef-(jline,2.12) | sparkVersion-2.1.0 | withHive-true |.`

**Comment by vidma** [comment]
check this diff, likely you need to add these lines to your `conf/application.conf` .
https://github.com/spark-notebook/spark-notebook/commit/b519c8ba45dc7809068d05fa6333b67f529075b9#diff-62ce533313cdad5202810504ca706009

**Comment by james64** [comment]
Hey, I experienced similar (not the same) issue with "old" version as well. This suggest that it might be a thing on our side.

The problem now is that I have not idea what am I looking for. Network? Configuration? It would be ideal if I can dig into SN code base of SN. But it is too complicated for me at first. That leads me to think. Is there any document describing tree structure of code base with simple hints like "this module contains this and that and communicates with that module over there". Or do you think it's worthy to create it? This would help me immensely to dive into code...

**Comment by james64** [comment]
For example: I have found that the last line I see in server log:
`INFO application: View notebook 'visnovy-jogurt.snb', presentation: 'None'`
is comming from openNotebook method of controllers.Application object. But I cannot find where this is called from...

**Comment by vidma** [comment]
such a doc don't exist yet, I think. 

Here's a few quick notes, feel free to create a better doc afterwards:

```
main interactions (data-flow):
 JavaScript [web] <-> Application.scala <-> WebSocketKernelActor (play app) <-> CalcWebSocketService   <- different JVM process -> ReplCalculator <-> Repl


Code structure:
- conf/routes - makes URLs to play Application backend
- app: is a Play-app web-backend
- modules/  (some sub-projects have a README.md file inside!)
  * core -  basic stuff, e.g. for reading/writing SNB files
  * common (included by most modules/JVM processes)
  * git-notebook-provider  - git storage support, used only if enabled
  * kernel - a REPL which is run a separate JVM process, per each notebook
    * `ReplCalculator` process the commands, and passes them to `Repl` for execution (a patched/improved spark-shell/repl for apache-spark)
   * stuff is passed over as akka actor messages:
     - Javascript sends commands to execute
     - executes them, and sends back the result DIRECTLY to javascript via observable
     - Javascript stores/send the notebook file which contain command results
```

P.S. IntellijIDEA Ultimate helps to orient yourself inside a large `Play! framework` project (e.g. `conf/routes` are navigatable there).

**Comment by vidma** [comment]
also be sure to check both:
- logs in your browser console (when openned a notebook)
- logs of spark-notebook server ...

**Comment by james64** [comment]
Hello guys I have finally found some time to investigate this more.

Now old version works while new one doesn't (see above for versions info) in same environment. So there probably is something different in snb.

Going through code base and all logs I see that the process of loading a notebook in new version is stuck on creating a web sockets. Last log I see in browser console is this:
`kernel.js:446 Starting WebSockets: ws://localhost:9210/ws/api/kernels/1782ae91-5483-432c-9e80-adc3ac66e56b`

...and then silence. First line I do **not** see in server log (compared to when it works) is this one:
`INFO application: Registering first web-socket (notebook.server.WebSockWrapperImpl@...`

I will try to dig deeper. Any ideas for what's happening or what to check appreciated.

Thnks

**Comment by james64** [comment]
I tried it with current master (see below) and it is stuck on starting websocket as well. I am going to look if I am able to compile arbitrary SN version myself. That way I can try to binary search and find the first commit which does not work for me...

`Build: |  buildTime-Sun May 14 11:21:44 UTC 2017 | formattedShaVersion-0.8.0-SNAPSHOT-5e22edb6e4facfc113704b1720df3b1bc6ff4d3a | sbtVersion-0.13.8 | scalaVersion-2.11.8 | sparkNotebookVersion-0.8.0-SNAPSHOT | viewer-false | hadoopVersion-2.6.0-cdh5.10.1 | jets3tVersion-0.7.1 | jlineDef-(jline,2.12) | sparkVersion-2.1.0 | withHive-false |.`

**Comment by james64** [comment]
So I tried to run SN locally from sbt console setting spark, hadoop, sbt and scala versions.
For git hash of version nicknamed 'old' at the beginning I was able to fire up local nb.
For git hash of version nicknamed 'new' at the beginning I got this weired error:

```
! @742jeadl5 - Internal server error, for (GET) [/api/contents/?type=directory&_=1494766852984] ->

@742jeadl5: Execution exception in null:null
        at play.api.Application$class.handleError(Application.scala:296)
        at play.api.DefaultApplication.handleError(Application.scala:402)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205)
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Failure.recover(Try.scala:216)
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
        at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:326)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
        at scala.concurrent.Promise$class.complete(Promise.scala:55)
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalArgumentException: 'other' is different type of Path
        at sun.nio.fs.UnixPath.relativize(UnixPath.java:416)
        at sun.nio.fs.UnixPath.relativize(UnixPath.java:43)
        at notebook.io.NotebookProvider$class.relativePath$1(NotebookProvider.scala:68)
        at notebook.io.NotebookProvider$$anonfun$list$1$$anonfun$apply$7.apply(NotebookProvider.scala:74)
        at notebook.io.NotebookProvider$$anonfun$list$1$$anonfun$apply$7.apply(NotebookProvider.scala:74)
        at scala.collection.immutable.List.map(List.scala:273)
        at notebook.io.NotebookProvider$$anonfun$list$1.apply(NotebookProvider.scala:74)
        at notebook.io.NotebookProvider$$anonfun$list$1.apply(NotebookProvider.scala:75)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        ... 4 more
```

**Comment by vidma** [comment]
well, see this exception is raised in:
        at sun.nio.fs.UnixPath.relativize(UnixPath.java:416)
so there's something wrong with the absolute dir where the notebooks are stored.

so:
- check if the directory isn't weird (maybe you have a symlink or whatever), and move SN to some regular dir.
  * P.S. in OSX, `/tmp/XYZ`  is resolved into `/private/tmp/XYZ`; similar stuff maybe might  cause problems
- set **an explicit ABSOLUTE path of notebooks dir** when starting spark-notebook:
```bash
export NOTEBOOKS_DIR="/some/absolute/path/spark-notebook/notebooks"
bin/spark-notebook
```

**Comment by james64** [comment]
Putting a directory issue aside (solved by notebooks_dir). By further experimenting I see that web-socket (main issue here) is not able to connect when I use:
`-D"hadoop.version"=2.6.0-cdh5.10.1`
instead of
`-D"hadoop.version"=2.6.0-cdh5.7.1`.

We now use `2.6.0-cdh5.10.1` on our cluster. Any idea how this might affect web-sockets?
Trying to dig deeper in a meantime.

**Comment by vidma** [comment]
yup, it that seems with this hadoop version, there's some connectivity problem (not yet sure where).
one random bet could be changed versions in some common libs, causing conflicts. I'd check for version changes in `akka`, `play*` etc.

browser console says:
```
Observable init delayed because kernel id not available (IPython.notebook.kernel.id)

Session: kernel_created (null)
kernel.js:446 Starting WebSockets: ws://localhost:9007/ws/api/kernels/a01d5eef-d832-4fe4-9116-62c25abcd9c0
observable.js:117 Creating new observable (client request): anon357ecfc9e6bb7aa542adff7372d0c287
observable.js:123 Delaying the registration of Observable (anon357ecfc9e6bb7aa542adff7372d0c287) since Observable isn't initialized yet

Can't execute, kernel is not connected.
```

**Comment by james64** [comment]
It looks that only dependency where hadoop version is used is hadoop-client. So I diffed
`org.apache.hadoop:hadoop-client:2.6.0-cdh5.7.1` and
`org.apache.hadoop:hadoop-client:2.6.0-cdh5.10.1`.

These are the differences in newer version excluding `org.apache.hadoop` artifacts:
- libs under `com.fasterxml.jackson.core` groupID updated
- added `com.amazonaws:aws-java-sdk-sts:1.10.16`
- version of `io.netty:netty` updated from `3.7.0.Final` to `3.10.5.Final`
- version change of `org.codehaus.jackson:jackson-core-asl` and of `org.codehaus.jackson:jackson-mapper-asl` from `1.8.8` to `1.9.13`

Is netty a suspicious one?

**Comment by vidma** [comment]
first beware it's the CDH versions which changed, and not the hadoop version!

yeah, netty might be quite suspicious (play uses netty, and spark too, and if you have hadoop too, well you know...!). 
I'm currently yesterday was fighting some horrible jar-hell with it in #857 (see https://github.com/spark-notebook/spark-notebook/pull/857/commits/b864d61e718b3a08fd12a873bece491ca41f7d20 and https://github.com/spark-notebook/spark-notebook/pull/857/commits/48b14d5109dd6b1b9ed63ea172286462a97e2977 : netty organisation changed in the past. from org.jboss.netty to io.netty, but they contain the same package), but I'm not sure if that's related.

also for fun you may try `sbt -Dakka.jvm-exit-on-fatal-error=on <other options> clean test run`

**Comment by james64** [comment]
Last version of cloudera where this works is `cdh5.8.5`. Next one `cdh5.9.0` has this issue. There is only one change in transitive dependencies (apart from cdh stuff) and yup that is netty:
`io.netty:netty:3.7.0.Final` to `io.netty:netty:3.10.5.Final`

**Comment by james64** [comment]
I have tried to run the code with that `akka.jvm-exit` thing and tried it again. Websocket not able to connect again. There was no exception raised.

Is there further way I can help?

**Comment by vidma** [comment]
@james64 just try the newest spark-notebook master. I added plenty of old `netty` excludes.

**Comment by james64** [comment]
I tried with latest master including your commit and web-socket still does not work...
