### ISSUE TITLE
Using built-in Hive

### ISSUE THREAD

**Issue by rinnyB** [spark-notebook/spark-notebook#842]
Hello!
I'm pretty new to Spark-Notebook, I need to perform some very simple interactions with Hive Tables (Trying to make SparkSQL examples to work).
I'm using spark-notebook's `sparkSession` for this:
``` scala
val spark = sparkSession
import spark.sql
import spark.implicits._
sql("create table tests(key INT, value STRING)") // done OK
sql("LOAD DATA LOCAL INPATH 'kv1.txt' INTO TABLE tests") 
```
And the error I encounter is:
``` 
java.lang.UnsupportedOperationException: loadTable is not implemented
  at org.apache.spark.sql.catalyst.catalog.InMemoryCatalog.loadTable(InMemoryCatalog.scala:316)
  at org.apache.spark.sql.catalyst.catalog.SessionCatalog.loadTable(SessionCatalog.scala:319)
  at org.apache.spark.sql.execution.command.LoadDataCommand.run(tables.scala:302)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:87)
  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:87)
  at org.apache.spark.sql.Dataset.<init>(Dataset.scala:185)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:592)
```
Or trying to `INSERT` stuff manually:
``` scala
sql("insert into table tests values (1, 'whoa')")
```
The error is:
```
org.apache.spark.sql.AnalysisException:
Hive support is required to insert into the following tables:
`default`.`tests`
               ;;
'InsertIntoTable 'SimpleCatalogRelation default, CatalogTable(
	Table: `default`.`tests`
	Created: Tue Apr 18 16:21:14 EEST 2017
	Last Access: Thu Jan 01 02:59:59 EET 1970
	Type: MANAGED
	Schema: [StructField(key,IntegerType,true), StructField(value,StringType,true)]
	Provider: hive
	Storage(Location: file:/home/mika/Desktop/spark-notebook-0.7.0-scala-2.11.8-spark-2.1.0-hadoop-2.6.0-cdh5.4.2-with-hive/spark-warehouse/tests, InputFormat: org.apache.hadoop.mapred.TextInputFormat, OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat)), OverwriteOptions(false,Map()), false
+- LocalRelation [col1#6, col2#7]

  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.failAnalysis(CheckAnalysis.scala:40)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.failAnalysis(Analyzer.scala:57)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:383)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:67)
  at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:128)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:67)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:57)
  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:48)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:63)
  at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:592)
```

I've also tried to do it in the Spark's "official" way:

``` scala
val warehouseLocation = "spark-warehouse"
val Hive = SparkSession
  .builder()
  .appName("Spark Hive Example")
  .config("spark.sql.warehouse.dir", warehouseLocation)
  .enableHiveSupport()
  .getOrCreate()
```
Still same errors.

Right now I'm trying to use spark-notebook-0.7.0-scala-2.11.8-spark-2.1.0-hadoop-2.6.0-cdh5.4.2-with-hive under Ubuntu 16.04 VM. 
I launch spark-notebook with:
cd %notebook-dir%
./bin/spark-notebook
(there is something strange with paths when launching from /bin directly, 
it can't find notebook folder then)

I've tried chmod-ing and chown-ing folders for 777 and my user, launching notebook with sudo, yet this gave me no results.
 I've downloaded a dozen of different spark-notebook versions (master, 0.7 ones, and more), but i encounter same problem every time.

Maybe, I just do something wrong.
Thanks in advance.

**Comment by vidma** [comment]
this might be a known issue I think. try setting `spark.sql.catalogImplementation=hive` spark-conf.

e.g. you can start SN server with this added to force it:
```
-Dmanager.notebooks.override.sparkConf.spark.sql.catalogImplementation=hive \
 "-Dmanager.notebooks.override.sparkConf.spark.sql.warehouse.dir=hdfs://namenode:8020/user/hive/warehouse"
````
see here: https://github.com/spark-notebook/spark-notebook/pull/731#issuecomment-257386380
