### ISSUE TITLE
java.lang.ClassNotFoundException Spark streaming kafka.

### ISSUE THREAD

**Issue by rezacute** [spark-notebook/spark-notebook#856]
I am using spark-notebook with spark 2.1.1 and kafka 0.10.
the notebook can not find class on the runtime.

below is the log.

Thanks...
```
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
  at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:702)
  at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:557)
  at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:540)
  at org.apache.spark.streaming.kafka010.Subscribe.onStart(ConsumerStrategy.scala:83)
  at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.consumer(DirectKafkaInputDStream.scala:75)
  at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.start(DirectKafkaInputDStream.scala:243)
  at org.apache.spark.streaming.DStreamGraph$$anonfun$start$5.apply(DStreamGraph.scala:49)
  at org.apache.spark.streaming.DStreamGraph$$anonfun$start$5.apply(DStreamGraph.scala:49)
  at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
  at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
  at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
  at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
  at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
  at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
  at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
  at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
  at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
  at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
  at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
  at ... run in separate thread using org.apache.spark.util.ThreadUtils ... ()
  at org.apache.spark.streaming.StreamingContext.liftedTree1$1(StreamingContext.scala:577)
  at org.apache.spark.streaming.StreamingContext.start(StreamingContext.scala:571)
  ... 65 elided
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.clients.consumer.RangeAssignor ClassNotFoundException exception occured
  at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:227)
  at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:637)
  at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:557)
  at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:540)
  at org.apache.spark.streaming.kafka010.Subscribe.onStart(ConsumerStrategy.scala:83)
  at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.consumer(DirectKafkaInputDStream.scala:75)
  at org.apache.spark.streaming.kafka010.DirectKafkaInputDStream.start(DirectKafkaInputDStream.scala:243)
  at org.apache.spark.streaming.DStreamGraph$$anonfun$start$5.apply(DStreamGraph.scala:49)
  at org.apache.spark.streaming.DStreamGraph$$anonfun$start$5.apply(DStreamGraph.scala:49)
  at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:143)
  at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:136)
  at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:972)
  at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:49)
  at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
  at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:48)
  at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:51)
  at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:969)
  at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:152)
  at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:443)
  at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
  ... 4 more
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.clients.consumer.RangeAssignor
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at java.lang.Class.forName0(Native Method)
  at java.lang.Class.forName(Class.java:348)
  at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:332)
  at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstances(AbstractConfig.java:225)
  ... 23 more
```

**Comment by vidma** [comment]
most likely guesses:
- maybe you forgot to ship some kafka jars to executors?
- in case of jar conflicts an error message is usually also similar

**Comment by rezacute** [comment]
I have already set dependencies on notebook metadata

**Comment by maasg** [comment]
@rezacute @vidma I'm observing the same error.   I think it comes from this dynamic class loading: https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/config/AbstractConfig.java#L246
Not sure why the kernel cannot find that class.
This works on the notebook without issue:
```scala
val freakingClass = classOf[org.apache.kafka.clients.consumer.RangeAssignor].newInstance()
freakingClass: org.apache.kafka.clients.consumer.RangeAssignor = org.apache.kafka.clients.consumer.RangeAssignor@3281a62b
```
Not sure what's up here.

**Comment by rezacute** [comment]
@maasg , yeah i think it is class loader issue. If anybody can do streaming with kafka 0.10.x on spark-notebook please share.

**Comment by vidma** [comment]
@rezacute if you shared a minimum failing snb notebook file, it would be easier to help you out.
and which scala version do you use?

also, in addition to [maasg comment](https://github.com/spark-notebook/spark-notebook/issues/856#issuecomment-313955390),  check if this error happens on the `driver` or the `executor` nodes? do the executor nodes really have the Kafka classes available 
(I guess you used `customDeps` in notebook-metadata, right?)...

**Comment by maasg** [comment]
This notebook reproduces the issue.
Easiest way to reproduce is running `spotify/kafka`:
```
docker run -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=127.0.0.1 --env ADVERTISED_PORT=9092 spotify/kafka
```
[kafka010-streaming-data.snb.zip](https://github.com/spark-notebook/spark-notebook/files/1135681/kafka010-streaming-data.snb.zip)

Going back to the 0.8 consumer works.

**Comment by vamshireddy21** [comment]
Did you guys had the fix for this issue
