### ISSUE TITLE
Cannot read or write Files in spark standalone mode

### ISSUE THREAD

**Issue by LarryDarrell** [spark-notebook/spark-notebook#866]
I was using spark-notebook-0.7.0(scala-2.11.8, spark-2.1.0, hadoop-2.7.2, with-hive) in a docker container and everything went well when the notebook runs in local mode.  I tried the spark standalone mode today and found out that I failed to read/write files. (The same code works well in spark notebook local mode or in spark-shell).

# Fail to Write
When I executed the following code:
```scala
val data = Array(1, 2, 3, 4, 5)
val data1 = sc.parallelize(data)
val data2 = data1.collect()
sc.parallelize(data2).saveAsTextFile("/opt/work/sampleData3")
``` 
I got the log message:
```
data: Array[Int] = Array(1, 2, 3, 4, 5)
data1: org.apache.spark.rdd.RDD[Int] = ParallelCollectionRDD[0] at parallelize at <console>:69
data2: Array[Int] = Array(1, 2, 3, 4, 5)
```
There is a sampleData3 folder with a _SUCCESS file, however without part-XXXX. I failed to find the final partition in my spark client, spark worker and spark master.

There was nothing wrong with the collect() command:
```scala
val data2 = data1.collect()
```

# Fail to Read 
When I executed the following code:
```scala
val textFile = sc.textFile("/opt/work/spark-notebook/README.md")
textFile.count()
```
I got the error messages below. (the README.md file does exist)
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 6.0 failed 4 times, most recent failure: Lost task 1.3 in stage 6.0 (TID 33, 192.168.0.215, executor 1): java.io.FileNotFoundException: File file:/opt/work/spark-notebook/README.md does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:611)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:824)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:601)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:421)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:142)
	at org.apache.hadoop.fs.ChecksumFileSystem.open(ChecksumFileSystem.java:346)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:769)
	at org.apache.hadoop.mapred.LineRecordReader.<init>(LineRecordReader.java:109)
	at org.apache.hadoop.mapred.TextInputFormat.getRecordReader(TextInputFormat.java:67)
	at org.apache.spark.rdd.HadoopRDD$$anon$1.liftedTree1$1(HadoopRDD.scala:252)
	at org.apache.spark.rdd.HadoopRDD$$anon$1.<init>(HadoopRDD.scala:251)
	at org.apache.spark.rdd.HadoopRDD.compute(HadoopRDD.scala:211)
	at org.apache.spark.rdd.HadoopRDD.compute(HadoopRDD.scala:102)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by vidma** [comment]
smells like an issue with spark itself or configuration.

**Comment by maasg** [comment]
When you work in a cluster, all executors need to have access to a shared
file storage. This is typically HDFS but could also be a distributed
database ooit a classical rdbms.
The error you are seeing is that each Spark executor is trying to read o
write from that local path you specified. In the write case, partitions are
written on each node from the clusters, leaving you with a scattered file.
In the read case, the file does not exist in the executors and gives a fire
not found.
When moving to a cluster, you need the proper storage to cope with the
distributed nature of Spark.

The good news is that all your configuration is working properly, so you
need just few additional steps to have a working distributed environment

Hope this helps.
-Gerard

**Comment by LarryDarrell** [comment]
@maasg 
Thank you for your reply. I also believe that HDFS can solve this problem. But I want to know why the local file system fails? In my opinion, spark notebook assigns the job to spark-shell or spark-submit eventually. Therefore, I am wondering why the same code can run in the spark-shell whilw the spark notebook fails?
```bash
./bin/spark-shell --master spark://url:port
```

**Comment by LarryDarrell** [comment]
@vidma 
Thank your for your support. I guess the local file system is the cause as maasg suggests.

**Comment by LarryDarrell** [comment]
I deployed Spark Notebook is AWS in a same manner and I could read/write local files in Spark. I guess there is something wrong with my local spark configurations and the issue is not related to Spark notebook.
