### ISSUE TITLE
Simple Parquet file fails with org.apache.spark.InterruptibleIterator cannot be cast to org.apache.spark.sql.types.StructField

### ISSUE THREAD

**Issue by fabboe** [spark-notebook/spark-notebook#874]
spark-notebook-0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.7.3-with-hive

```
val spark = SparkSession.builder.getOrCreate()
```
and reading a basic Parquet file (spark.write.parquet) `with spark.read.parquet` fails with:

```

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 3.0 failed 4 times, most recent failure: Lost task 0.3 in stage 3.0 (TID 15, prtlap04, executor 1): java.lang.ClassCastException: org.apache.spark.InterruptibleIterator cannot be cast to org.apache.spark.sql.types.StructField
	at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$$anonfun$12.apply(ParquetFileFormat.scala:513)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


```

**Comment by fabboe** [comment]
Had some extra jars added with a different Spark version, nvm.

**Comment by githubMukund** [comment]
Hi fabboe, I am getting the same error. Can you please help me with what extra jars did you add?.
