### ISSUE TITLE
"Oops, cannot start the server."

### ISSUE THREAD

**Issue by davidecarneiro** [spark-notebook/spark-notebook#893]
Hi,
I was starting a spark notebook for the first time and I get the error transcribed bellow. It seems to search for an "application.conf" file which does exist in the "conf" directory. What does NOT exist is another file named "SPARK_NOTEBOOK_config.txt" which, as I understand from the launcher script, should exist in the home directory?

I tried setting a SPARK_NOTEBOOK_HOME environment variable to point to the folder I unzipped but to no avail. 

Any clues? Thanks in advance, error below.

Oops, cannot start the server.
Configuration error: Configuration error[application: application.conf: java.io.IOException: resource not found on classpath: application.conf, application.json: java.io.IOException: resource not found on classpath: application.json, application.properties: java.io.IOException: resource not found on classpath: application.properties]
        at play.api.Configuration$.configError(Configuration.scala:155)
        at play.api.Configuration$.load(Configuration.scala:101)
        at play.api.Configuration$.load(Configuration.scala:109)
        at play.api.ApplicationLoader$.createContext(ApplicationLoader.scala:94)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:45)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:22)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: com.typesafe.config.ConfigException$IO: application: application.conf: java.io.IOException: resource not found on classpath: application.conf, application.json: java.io.IOException: resource not found on classpath: application.json, application.properties: java.io.IOException: resource not found on classpath: application.properties
        at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:236)
        at com.typesafe.config.impl.ConfigImpl.parseResourcesAnySyntax(ConfigImpl.java:132)
        at com.typesafe.config.ConfigFactory.parseResourcesAnySyntax(ConfigFactory.java:978)
        at com.typesafe.config.DefaultConfigLoadingStrategy.parseApplicationConfig(DefaultConfigLoadingStrategy.java:36)
        at com.typesafe.config.ConfigFactory.defaultApplication(ConfigFactory.java:473)
        at play.api.Configuration$$anonfun$3.apply(Configuration.scala:73)
        at play.api.Configuration$$anonfun$3.apply(Configuration.scala:69)
        at scala.Option.getOrElse(Option.scala:121)
        at play.api.Configuration$.load(Configuration.scala:69)
        ... 5 more
Caused by: com.typesafe.config.ConfigException$IO: application.conf: java.io.IOException: resource not found on classpath: application.conf
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:188)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
        at com.typesafe.config.impl.Parseable.parse(Parseable.java:152)
        at com.typesafe.config.impl.SimpleIncluder.fromBasename(SimpleIncluder.java:185)
        ... 13 more
Caused by: java.io.IOException: resource not found on classpath: application.conf
        at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:735)
        at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:710)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
        ... 16 more

My build:
OS: Windows
notebook version : master
scala version : 2.11.8
spark version : 2.1.1
spark nightly : false
hadoop version : 2.7.2
with hive : true
with parquet : true
package type : zip

**Comment by vidma** [comment]
I think you need to run it like this:

    $ bin/spark-notebook -Dconfig.file=conf/application.conf  # or path to your custom config file

 or maybe like this if that needs the bloody windows-style paths ;)

    $ bin/spark-notebook -Dconfig.file=conf\application.conf  # or path to your custom config file

let us know if that helped, and if you faced any other issues.  unfortunately, we rarely have the possibility to test it with windows...

**Comment by davidecarneiro** [comment]
Still does not work. However I have been able to use spark-notebook from docker without a problem. Thank you!

**Comment by markpavey** [comment]
To get it to work on Windows I had to edit the file bin\spark-notebook.bat.

There is a line that sets the application classpath (line 132 in my build) and I had to add the conf directory to it:

set "APP_CLASSPATH=%CLASSPATH_OVERRIDES%;%YARN_CONF_DIR%;%HADOOP_CONF_DIR%;%EXTRA_CLASSPATH%;**%APP_LIB_DIR%\..\conf;**%APP_CLASSPATH%"

I figured this out by comparing with the bin\spark-notebook bash script where the conf directory is already added to the classpath.

Is there a better way to do this or should this change be added to the build?
