### ISSUE TITLE
Loading redshift driver - spark-redshift from databricks

### ISSUE THREAD

**Issue by guruattimeinc** [spark-notebook/spark-notebook#904]
Hi,
I am trying to connect to redshift from notebook, so far i have done following -

1. Configured metadata for the notebook 
 ```
"customDeps": [
    "com.databricks:spark-redshift_2.10:3.0.0-preview1",
    "com.databricks:spark-avro_2.11:3.2.0",
    "com.databricks:spark-csv_2.11:1.5.0"
]
```
2. Checked browser console to ensure this library is loaded after restarting kernel
```
ui-logs-1422> [Tue Aug 22 2017 09:46:26 GMT+0530 (IST)] [notebook.util.CoursierDeps$] Fetched artifact to:/Users/xxxx/.m2/repository/com/databricks/spark-avro_2.10/3.0.0/spark-avro_2.10-3.0.0.jar
kernel.js:978 ui-logs-1452> [Tue Aug 22 2017 09:46:26 GMT+0530 (IST)] [notebook.util.CoursierDeps$] Fetched artifact to:/Users/xxxx/.coursier/cache/v1/http/repo1.maven.org/maven2/com/databricks/spark-redshift_2.10/3.0.0-preview1/spark-redshift_2.10-3.0.0-preview1.jar
kernel.js:978 ui-logs-1509> [Tue Aug 22 2017 09:46:26 GMT+0530 (IST)] [notebook.util.CoursierDeps$] Fetched artifact to:/Users/xxxx/.coursier/cache/v1/http/repo1.maven.org/maven2/com/databricks/spark-csv_2.11/1.5.0/spark-csv_2.11-1.5.0.jar
kernel.js:978 ui-logs-1526> [Tue Aug 22 2017 09:46:26 GMT+0530 (IST)] [notebook.util.CoursierDeps$] Fetched artifact to:/Users/xxxx/.coursier/cache/v1/http/repo1.maven.org/maven2/com/databricks/spark-avro_2.11/3.2.0/spark-avro_2.11-3.2.0.jar
```
3. When i try to load a table - i run into class not found exception,
```
java.lang.ClassNotFoundException: Failed to find data source: com.databricks.spark.redshift. Please find packages at http://spark.apache.org/third-party-projects.html
  at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:594)
  at org.apache.spark.sql.execution.datasources.DataSource.providingClass$lzycompute(DataSource.scala:86)
  at org.apache.spark.sql.execution.datasources.DataSource.providingClass(DataSource.scala:86)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:325)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:125)
  ... 63 elided
Caused by: java.lang.ClassNotFoundException: com.databricks.spark.redshift.DefaultSource
  at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:62)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$25$$anonfun$apply$13.apply(DataSource.scala:579)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$25$$anonfun$apply$13.apply(DataSource.scala:579)
  at scala.util.Try$.apply(Try.scala:192)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$25.apply(DataSource.scala:579)
  at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$25.apply(DataSource.scala:579)
  at scala.util.Try.orElse(Try.scala:84)
  at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:579)
```

Anyone else running into this issue or have solved this?

-
Thanks

**Comment by guruattimeinc** [comment]
I notice similar issue with another dependency as well, is there any thing missing in the configuration?

1. Trying out timeseries sample in the notebook - notebooks/timeseries/Spark-Timeseries.snb.ipynb
2. Notice an existing entry in metadata for custom dependency - 
```
"customDeps": [
    "com.cloudera.sparkts % sparkts % 0.3.0"
  ]
```
Quickly verified availability of this package @ https://spark-packages.org/package/sryza/spark-timeseries
(updated meta data to include this line)
```
    "com.cloudera.sparkts:sparkts:0.4.1"

```
3. After restarting kernel - validated library is loaded
```
ui-logs-337> [Wed Aug 23 2017 09:29:25 GMT+0530 (IST)] [notebook.util.CoursierDeps$] Will fetch these customDeps artifacts:Set(Dependency(com.cloudera.sparkts:sparkts,0.3.0,,Set(),Attributes(,),false,true), Dependency(com.cloudera.sparkts:sparkts,0.4.1,,Set(),Attributes(,),false,true))
kernel.js:978 ui-logs-347> [Wed Aug 23 2017 09:29:37 GMT+0530 (IST)] [notebook.util.CoursierDeps$] Fetched artifact to:/Users/xxxx/.coursier/cache/v1/http/repo1.maven.org/maven2/com/cloudera/sparkts/sparkts/0.4.1/sparkts-0.4.1.jar
```

Error message -

```
<console>:69: error: object cloudera is not a member of package com
       import com.cloudera.sparkts._
                  ^
<console>:70: error: object cloudera is not a member of package com
       import com.cloudera.sparkts.stats.TimeSeriesStatisticalTests
```

**Comment by vidma** [comment]
@guruattimeinc  beware `sparkts:sparkts` available version depends on scala version and likely on spark version too.
e.g. https://mvnrepository.com/artifact/com.cloudera.sparkts/sparkts/0.4.1 uses scala 2.11. 

so you likely need to match the versions, or maybe in the newer version of `sparkts:sparkts` its API has changed.

feel free to make an updated sample notebook (with a different name which would work with your version of spark / scala).

**Comment by vidma** [comment]
@guruattimeinc 
sorry for a late reply (I was very busy).

regarding  redshift, notice that you should NEVER mix scala `2.10` and `2.11`. This is the most likely cause of not found classes (though there might be some other issues afterwards).
you need to choose the one scala version, and use spark-notebook and Spark compiled for that single scala major version.
```
   "com.databricks:spark-redshift_2.10:3.0.0-preview1",
   "com.databricks:spark-avro_2.11:3.2.0",
   "com.databricks:spark-csv_2.11:1.5.0"
```

Cheers, v

**Comment by guruattimeinc** [comment]
Thanks for the response, i got all the versions lined up.
//This is what my notebook is using
```
Scala [2.11.8] Spark [2.1.1] Hadoop [2.7.2]
```
//Dependency configured
```
    "com.databricks:spark-redshift_2.11:3.0.0-preview1",
    "com.databricks:spark-avro_2.11:3.2.0",
    "com.databricks:spark-csv_2.11:1.5.0",
    "com.amazonaws:aws-java-sdk:1.11.179"
```
and confirmed the library loading in console -
```
ui-logs-230> [Tue Aug 29 2017 09:37:28 GMT+0530 (IST)] [notebook.util.CoursierDeps$] Will fetch these customDeps artifacts:Set(Dependency(com.databricks:spark-redshift_2.11,3.0.0-preview1,,Set(),Attributes(,),false,true), Dependency(com.databricks:spark-avro_2.11,3.2.0,,Set(),Attributes(,),false,true), Dependency(com.databricks:spark-csv_2.11,1.5.0,,Set(),Attributes(,),false,true), Dependency(com.amazonaws:aws-java-sdk,1.11.179,,Set(),Attributes(,),false,true))
kernel.js:978 ui-logs-304> [Tue Aug 29 2017 09:37:32 GMT+0530 (IST)] [notebook.util.CoursierDeps$] Fetched artifact to:/Users/ramaraog/.coursier/cache/v1/http/repo1.maven.org/maven2/com/databricks/spark-redshift_2.11/3.0.0-preview1/spark-redshift_2.11-3.0.0-preview1.jar
kernel.js:978 ui-logs-324> [Tue Aug 29 2017 09:37:32 GMT+0530 (IST)] [notebook.util.CoursierDeps$] Fetched artifact to:/Users/ramaraog/.coursier/cache/v1/http/repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-redshift/1.11.179/aws-java-sdk-redshift-1.11.179.jar
```

end result still the same -
```
java.lang.ClassNotFoundException: Failed to find data source: com.databricks.spark.redshift. Please find packages at http://spark.apache.org/third-party-projects.html
  at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:594)
  at org.apache.spark.sql.execution.datasources.DataSource.providingClass$lzycompute(DataSource.scala:86)
  at org.apache.spark.sql.execution.datasources.DataSource.providingClass(DataSource.scala:86)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:325)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:125)
  ... 63 elided
Caused by: java.lang.ClassNotFoundException: com.databricks.spark.redshift.DefaultSource
```

**Comment by guruattimeinc** [comment]
Thanks again for the response. I downloaded spark-notebook not in master branch, used custom dependencies approach explained above and this solved my problem. I had to use 
```
EXTRA_CLASSPATH=RedshiftJDBC4-1.2.7.1003.jar
```
as i couldnt get redshift JDBC driver from maven repository. This might help others.
