### ISSUE TITLE
No Kernel starting up, "Key Not Found"

### ISSUE THREAD

**Issue by raproth** [spark-notebook/spark-notebook#920]
Using SN Version 0.7 I encountered a problem several times: Without any obvious reason (no changes to the notebook content or configuration), I cannot start up a notebook. The notebook opens, but I no kernel is starting up, also no logfile is created. I see in application.log:

```
2017-11-10 13:30:20,223 - [INFO] - from application in play-akka.actor.default-dispatcher-369
Loading notebook at path MyNotebook.snb

2017-11-10 13:30:22,351 - [ERROR] - from play in play-akka.actor.default-dispatcher-369
Cannot invoke the action, eventually got an error: java.util.NoSuchElementException: key not found: a067e818-0513-46ab-ac76-f2597fbaeba0

2017-11-10 13:30:22,352 - [ERROR] - from application in play-akka.actor.default-dispatcher-369


! @76128l8g8 - Internal server error, for (POST) [/api/sessions] ->

play.api.Application$$anon$1: Execution exception[[NoSuchElementException: key not found: a067e818-0513-46ab-ac76-f2597fbaeba0]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [
com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [
com.typesafe.play.play_2.10-2.3.10.jar:2.3.10]
        at scala.Option.map(Option.scala:145) [org.scala-lang.scala-library-2.10.5.jar:na]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play
.play_2.10-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:316) [com.typesafe.play
.play_2.10-2.3.10.jar:2.3.10]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.10.5.jar:na]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.10.5.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.10.5.jar:na]
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46) [com.typesafe.play.play-iteratees_2.10-2.4.0-M1.jar:2.4.
0-M1]
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40) [org.scala-lang.scala-library-2.10.5.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248) [org.scala-lang.scala-library-2.10.5.jar:na]
        at scala.concurrent.Promise$class.complete(Promise.scala:55) [org.scala-lang.scala-library-2.10.5.jar:na]
        at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153) [org.scala-lang.scala-library-2.10.5.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23) [org.scala-lang.scala-library-2.10.5.jar:na]
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) [com.typesafe.akka.akka-actor_2.10-2.3.11.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka.akka-actor_2.10
-2.3.11.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.5.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.10.5.jar:na]
Caused by: java.util.NoSuchElementException: key not found: a067e818-0513-46ab-ac76-f2597fbaeba0
        at scala.collection.MapLike$class.default(MapLike.scala:228) ~[org.scala-lang.scala-library-2.10.5.jar:na]
```

Any idea what that is? 

PS: The only solution I found to get the notebook running again is to make a copy of the notebook which will run just fine. I find that quite strange

**Comment by vidma** [comment]
sounds strange too. would restarting a SN server help?

also 0.7 is a rather old release ;)

P.S. it seems it thinks kernel for a given notebook should be still alive, while it isn't. might be a bug too, or kernel might have died in some very strange way...

this (most likely) comes from:

```
(POST) [/api/sessions] -> Application.createSession -> newSession()

  https://github.com/spark-notebook/spark-notebook/blob/branch-0.7/app/controllers/Application.scala#L217-L223

https://github.com/spark-notebook/spark-notebook/blob/branch-0.7/app/controllers/Application.scala#L104-L215
