### ISSUE TITLE
NoSuchMethodException: org.apache.spark.ui.SparkUI.appUIAddress() on spark 2.2

### ISSUE THREAD

**Issue by afewnotes** [spark-notebook/spark-notebook#922]
build details: 

>notebook version : master
scala version : 2.11.8
spark version : 2.2.0
spark nightly : false
hadoop version : 2.7.2
with hive : true
with parquet : true
package type : zip

env: Windows 10, Jdk 8

error details:
```
Exception in thread "Thread-13" java.lang.NoSuchMethodException: org.apache.spark.ui.SparkUI.appUIAddress()
        at java.lang.Class.getMethod(Class.java:1786)
        at org.apache.spark.ui.notebook.front.gadgets.SparkMonitor$$anonfun$2.apply(SparkMonitor.scala:44)
        at org.apache.spark.ui.notebook.front.gadgets.SparkMonitor$$anonfun$2.apply(SparkMonitor.scala:43)
        at scala.Option.map(Option.scala:146)
        at org.apache.spark.ui.notebook.front.gadgets.SparkMonitor.sparkUiLink(SparkMonitor.scala:43)
        at org.apache.spark.ui.notebook.front.gadgets.SparkMonitor$$anon$1.run(SparkMonitor.scala:147)
```

**Comment by vidma** [comment]
this shouldn't prevent spark-notebook from working OK, right?

only this is logged as an error and there's no `Spark UI` link...?

so apparently, spark 2.2.x changed this method... will need to update 
https://github.com/spark-notebook/spark-notebook/blob/a746b48b7ac376f2e8edea73e50d435640620308/modules/common/src/main/scala/notebook/front/gadgets/SparkMonitor.scala#L38-L50

**Comment by zhang-yuan** [comment]
you're right @vidma , thanks for your response

**Comment by antonkulaga** [comment]
I recently had a lot of headache because of this

**Comment by vidma** [comment]
@antonkulaga maybe you have started improving this? any PR/diff fixing this?
