### ISSUE TITLE
Cannot build due to missing commit

### ISSUE THREAD

**Issue by eddy-geek** [spark-notebook/spark-notebook#923]
Build fails on master when following steps from [build_specific_distro](https://github.com/spark-notebook/spark-notebook/blob/master/docs/build_specific_distros.md) :

```
git clone --depth 1 https://github.com/spark-notebook/spark-notebook
cd spark-notebook
sbt -Dspark.version=2.1.0-mapr-1707 -Dhadoop.version=2.7.0-mapr-1607 -Dwith.hive=true -Dwith.parquet=true clean dist
```

Relevant output:
```
org.eclipse.jgit.api.errors.JGitInternalException: Missing commit 1b8b5befdc9fab331cbe844b3077f47d2f1b9860
        at org.eclipse.jgit.api.DescribeCommand.call(DescribeCommand.java:282)
        at uk.gov.hmrc.gitstamp.GitStamp$.gitStamp(GitStamp.scala:36)
        at uk.gov.hmrc.gitstamp.GitStamp$.gitStamp(GitStamp.scala:30)
        at uk.gov.hmrc.gitstamp.GitStampPlugin$$anonfun$1.apply(GitStampPlugin.scala:29)
        at uk.gov.hmrc.gitstamp.GitStampPlugin$$anonfun$1.apply(GitStampPlugin.scala:28)
        at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:54)
        at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:53)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing commit 1b8b5befdc9fab331cbe844b3077f47d2f1b9860
        at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:149)
        at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:884)
        at org.eclipse.jgit.revwalk.RevCommit.parseHeaders(RevCommit.java:145)
        at org.eclipse.jgit.revwalk.PendingGenerator.next(PendingGenerator.java:148)
        at org.eclipse.jgit.revwalk.StartGenerator.next(StartGenerator.java:186)
        at org.eclipse.jgit.revwalk.RevWalk.next(RevWalk.java:422)
        at org.eclipse.jgit.api.DescribeCommand.call(DescribeCommand.java:223)
        at uk.gov.hmrc.gitstamp.GitStamp$.gitStamp(GitStamp.scala:36)
        at uk.gov.hmrc.gitstamp.GitStamp$.gitStamp(GitStamp.scala:30)
        at uk.gov.hmrc.gitstamp.GitStampPlugin$$anonfun$1.apply(GitStampPlugin.scala:29)
        at uk.gov.hmrc.gitstamp.GitStampPlugin$$anonfun$1.apply(GitStampPlugin.scala:28)
        at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:54)
        at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:53)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

The commit is not mentioned anywhere, the logs don't say which repository is affected... Any leads?

**Comment by vidma** [comment]
why do you use `--depth 1` ?
just do a regular `git clone`...
