### ISSUE TITLE
Run via Docker gives "java.lang.UnsupportedClassVersionError"

### ISSUE THREAD

**Issue by ebuildy** [spark-notebook/spark-notebook#926]
Running:

    docker run -p 9001:9001 -tid andypetrella/spark-notebook:0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.8.0-with-hive

Gives:

```
[debug] application - DASH ? /
[error] application -

! @768feg4c0 - Internal server error, for (GET) [/] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.UnsupportedClassVersionError: controllers/routes]]
	at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
	at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.8.jar:na]
Caused by: java.lang.RuntimeException: java.lang.UnsupportedClassVersionError: controllers/routes
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:523) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
Caused by: java.lang.UnsupportedClassVersionError: controllers/routes
	at views.html.projectdashboard$.apply(projectdashboard.template.scala:27) ~[nooostab.spark-notebook-0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.8.0-with-hive.jar:0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.8.0-with-hive]
	at controllers.Application$$anonfun$dash$1.apply(Application.scala:588) ~[nooostab.spark-notebook-0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.8.0-with-hive.jar:0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.8.0-with-hive]
	at controllers.Application$$anonfun$dash$1.apply(Application.scala:585) ~[nooostab.spark-notebook-0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.8.0-with-hive.jar:0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.8.0-with-hive]
	at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
	at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
```

This image is working fine: andypetrella/spark-notebook:0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.7.2

**Comment by leeivan** [comment]
I met same problem.

**Comment by frbayart** [comment]
Any reason to would like to use 0.7.0 ? It's an old release.

Else you can try this one:
`docker run -p 9000:9000 -tid andypetrella/spark-notebook:0.9.0-SNAPSHOT-scala-2.11.8-spark-2.1.1-hadoop-2.8.0-with-hive`

**Comment by vidma** [comment]
it usually means that JDK used is too old. 
if you use docker, just using a newer `spark-notebook` release should be enough.

> This class was compiled with a JDK more recent than the one used for execution

**Comment by AkbarAlam** [comment]
I am also having this error . Guys
```
[error] application -

! @78bjkdmhn - Internal server error, for (GET) [/] ->

play.api.Application$$anon$1: Execution exception[[RuntimeException: java.lang.UnsupportedClassVersionError: controllers/routes]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [org.scala-lang.scala-library-2.11.8.jar:na]Caused by: java.lang.RuntimeException: java.lang.UnsupportedClassVersionError: controllers/routes
        at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:523) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:130) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:129) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
Caused by: java.lang.UnsupportedClassVersionError: controllers/routes
        at views.html.projectdashboard$.apply(projectdashboard.template.scala:27) ~[nooostab.spark-notebook-0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.6.0-cdh5.10.1-with-hive.jar:0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.6.0-cdh5.10.1-with-hive]
        at controllers.Application$$anonfun$dash$1.apply(Application.scala:588) ~[nooostab.spark-notebook-0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.6.0-cdh5.10.1-with-hive.jar:0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.6.0-cdh5.10.1-with-hive]
        at controllers.Application$$anonfun$dash$1.apply(Application.scala:585) ~[nooostab.spark-notebook-0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.6.0-cdh5.10.1-with-hive.jar:0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.6.0-cdh5.10.1-with-hive]
        at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
        at play.api.mvc.ActionBuilder$$anonfun$apply$17.apply(Action.scala:464) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
```

**Comment by andypetrella** [comment]
Hello @AkbarAlam , could you please give the details of the versions you used, as it may help us unblocking you.

**Comment by AkbarAlam** [comment]
Unblock? from where? Why blocked from the first place? 
anyway, I am using the same command above which is

`docker run -p 9001:9001 -tid andypetrella/spark-notebook:0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.8.0-with-hive`

or you meant something else ?

**Comment by andypetrella** [comment]
Oh okay same image 

I’d recommend to use a newer version of spark notebook (0.8.0 or master for instance)

Then , looks like there is some crap in this image which should be generated again because indeed some java mismatch looks to be of the party ...

I may delete it so one could generate it again.

S’ry
